name = "Simple"
description = "Simple theme for roote.ca homepage"
homepage = "http://roote.ca/"
tags = []
features = []
min_version = "0.78.0"

[author]
  name = "Mitch Roote"
  homepage = "https://roote.ca"
