name: Deploy Hugo Static Site

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: get website artifact
      uses: actions/download-artifact@master
      with:
        name: homepage-website
        path: ./public
    - name: Backblaze B2 Sync
      uses: earendildev/backblaze-b2-action@v0.2.0
      env:
        SOURCE_DIR: './public'
        B2_BUCKET_PATH: 'b2://${{ secrets.B2_BUCKET }}/'
        B2_APPKEY_ID: ${{ secrets.B2_APPKEY_ID }}
        B2_APPKEY: ${{ secrets.B2_APPKEY }}
